name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Inject Google AdSense Code
        run: |
          if [ -n "${{ secrets.ADSENSE_CODE }}" ]; then
            # Save AdSense code to temporary file
            echo "${{ secrets.ADSENSE_CODE }}" > /tmp/adsense.txt
            # Use awk to replace placeholder with file content
            awk '
              /<!-- ADSENSE_CODE_PLACEHOLDER -->/ {
                system("cat /tmp/adsense.txt")
                next
              }
              { print }
            ' ./dist/index.html > /tmp/index.html.tmp
            mv /tmp/index.html.tmp ./dist/index.html
            rm /tmp/adsense.txt
            echo "✅ AdSense code injected successfully"
          else
            echo "⚠️ Warning: ADSENSE_CODE secret not set. Skipping AdSense injection."
          fi
        shell: bash
      
      - name: Deploy to Hostinger via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./dist/
          server-dir: /public_html/
          dangerous-clean-slate: true
